pipeline {
    agent any
    stages {
        stage('Clone') {
            steps { git 'https://github.com/YourUsername/cicd-pipeline-jenkins-docker-aws' }
        }
        stage('Build Docker Image') {
            steps { sh 'docker build -t myapp .' }
        }
        stage('Push to DockerHub') {
            steps { sh 'docker push YourDockerHub/myapp' }
        }
        stage('Deploy') {
            steps { sh 'docker run -d -p 80:80 YourDockerHub/myapp' }
        }
    }
}
